# Application configuration
spring.application.name=bakbak

# JPA Safety Configurations
spring.jpa.hibernate.ddl-auto=validate

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT configuration
jwt.secret=${JWT_SECRET}
# 7 days
jwt.expiration-ms=${JWT_EXPIRATION_MS:604800000}

# Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect